title: 'my bot with a name future '
description: >-
  This course is about my upcoming bot that I named "future" i want the bot can
  be helpful for generations to come 
template:
  repo: my-bot-with-a-name-future-template
  name: my-bot-with-a-name-future
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
